using System.Collections.Generic;

namespace Amanda
{
    class Gramaticas
    {
        #region Calculadora
        public static List<string> Numeros = new List<string>()
        {
            "zero",
            "um",
            "dois",
            "três",
            "quatro",
            "cinco",
            "seis",
            "sete",
            "oito",
            "nove",
            "dez",
            "onze",
            "doze",
            "treze",
            "quatorze",
            "quinze",
            "dezesseis",
            "dezessete",
            "dezoito",
            "dezenove",
            "vinte",
            "vinte e um",
            "vinte e dois",
            "vinte e três",
            "vinte e quatro",
            "vinte e cinco",
            "vinte e seis",
            "vinte e sete",
            "vinte e oito",
            "vinte e nove",
            "trinta",
            "trinta e um",
            "trinta e dois",
            "trinta e três",
            "trinta e quatro",
            "trinta e cinco",
            "trinta e seis",
            "trinta e sete",
            "trinta e oito",
            "trinta e nove",
            "quarenta",
            "quarenta e um",
            "quarenta e dois",
            "quarenta e três",
            "quarenta e quatro",
            "quarenta e cinco",
            "quarenta e seis",
            "quarenta e sete",
            "quarenta e oito",
            "quarenta e nove",
            "cinquenta",
            "cinquenta e um",
            "cinquenta e dois",
            "cinquenta e três",
            "cinquenta e quatro",
            "cinquenta e cinco",
            "cinquenta e seis",
            "cinquenta e sete",
            "cinquenta e oito",
            "cinquenta e nove",
            "sessenta",
            "sessenta e um",
            "sessenta e dois",
            "sessenta e três",
            "sessenta e quatro",
            "sessenta e cinco",
            "sessenta e seis",
            "sessenta e sete",
            "sessenta e oito",
            "sessenta e nove",
            "setenta",
            "setenta e um",
            "setenta e dois",
            "setenta e três",
            "setenta e quatro",
            "setenta e cinco",
            "setenta e seis",
            "setenta e sete",
            "setenta e oito",
            "setenta e nove",
            "oitenta",
            "oitenta e um",
            "oitenta e dois",
            "oitenta e três",
            "oitenta e quatro",
            "oitenta e cinco",
            "oitenta e seis",
            "oitenta e sete",
            "oitenta e oito",
            "oitenta e nove",
            "noventa",
            "noventa e um",
            "noventa e dois",
            "noventa e três",
            "noventa e quatro",
            "noventa e cinco",
            "noventa e seis",
            "noventa e sete",
            "noventa e oito",
            "noventa e nove",
            "cem",
            "cento e um",
            "cento e dois",
            "cento e três",
            "cento e quatro",
            "cento e cinco",
            "cento e seis",
            "cento e sete",
            "cento e oito",
            "cento e nove",
            "cento e dez",
            "cento e onze",
            "cento e doze",
            "cento e treze",
            "cento e quatorze",
            "cento e quinze",
            "cento e dezesseis",
            "cento e dezessete",
            "cento e dezoito",
            "cento e dezenove",
            "cento e vinte",
            "cento e vinte e um",
            "cento e vinte e dois",
            "cento e vinte e três",
            "cento e vinte e quatro",
            "cento e vinte e cinco",
            "cento e vinte e seis",
            "cento e vinte e sete",
            "cento e vinte e oito",
            "cento e vinte e nove",
            "cento e trinta",
            "cento e trinta e um",
            "cento e trinta e dois",
            "cento e trinta e três",
            "cento e trinta e quatro",
            "cento e trinta e cinco",
            "cento e trinta e seis",
            "cento e trinta e sete",
            "cento e trinta e oito",
            "cento e trinta e nove",
            "cento e quarenta",
            "cento e quarenta e um",
            "cento e quarenta e dois",
            "cento e quarenta e três",
            "cento e quarenta e quatro",
            "cento e quarenta e cinco",
            "cento e quarenta e seis",
            "cento e quarenta e sete",
            "cento e quarenta e oito",
            "cento e quarenta e nove",
            "cento e cinquenta",
            "cento e cinquenta e um",
            "cento e cinquenta e dois",
            "cento e cinquenta e três",
            "cento e cinquenta e quatro",
            "cento e cinquenta e cinco",
            "cento e cinquenta e seis",
            "cento e cinquenta e sete",
            "cento e cinquenta e oito",
            "cento e cinquenta e nove",
            "cento e sessenta",
            "cento e sessenta e um",
            "cento e sessenta e dois",
            "cento e sessenta e três",
            "cento e sessenta e quatro",
            "cento e sessenta e cinco",
            "cento e sessenta e seis",
            "cento e sessenta e sete",
            "cento e sessenta e oito",
            "cento e sessenta e nove",
            "cento e setenta",
            "cento e setenta e um",
            "cento e setenta e dois",
            "cento e setenta e três",
            "cento e setenta e quatro",
            "cento e setenta e cinco",
            "cento e setenta e seis",
            "cento e setenta e sete",
            "cento e setenta e oito",
            "cento e setenta e nove",
            "cento e oitenta",
            "cento e oitenta e um",
            "cento e oitenta e dois",
            "cento e oitenta e três",
            "cento e oitenta e quatro",
            "cento e oitenta e cinco",
            "cento e oitenta e seis",
            "cento e oitenta e sete",
            "cento e oitenta e oito",
            "cento e oitenta e nove",
            "cento e noventa",
            "cento e noventa e um",
            "cento e noventa e dois",
            "cento e noventa e três",
            "cento e noventa e quatro",
            "cento e noventa e cinco",
            "cento e noventa e seis",
            "cento e noventa e sete",
            "cento e noventa e oito",
            "cento e noventa e nove",
            "duzentos",
            "duzentos e um",
            "duzentos e dois",
            "duzentos e três",
            "duzentos e quatro",
            "duzentos e cinco",
            "duzentos e seis",
            "duzentos e sete",
            "duzentos e oito",
            "duzentos e nove",
            "duzentos e dez",
            "duzentos e onze",
            "duzentos e doze",
            "duzentos e treze",
            "duzentos e quatorze",
            "duzentos e quinze",
            "duzentos e dezesseis",
            "duzentos e dezessete",
            "duzentos e dezoito",
            "duzentos e dezenove",
            "duzentos e vinte",
            "duzentos e vinte e um",
            "duzentos e vinte e dois",
            "duzentos e vinte e três",
            "duzentos e vinte e quatro",
            "duzentos e vinte e cinco",
            "duzentos e vinte e seis",
            "duzentos e vinte e sete",
            "duzentos e vinte e oito",
            "duzentos e vinte e nove",
            "duzentos e trinta",
            "duzentos e trinta e um",
            "duzentos e trinta e dois",
            "duzentos e trinta e três",
            "duzentos e trinta e quatro",
            "duzentos e trinta e cinco",
            "duzentos e trinta e seis",
            "duzentos e trinta e sete",
            "duzentos e trinta e oito",
            "duzentos e trinta e nove",
            "duzentos e quarenta",
            "duzentos e quarenta e um",
            "duzentos e quarenta e dois",
            "duzentos e quarenta e três",
            "duzentos e quarenta e quatro",
            "duzentos e quarenta e cinco",
            "duzentos e quarenta e seis",
            "duzentos e quarenta e sete",
            "duzentos e quarenta e oito",
            "duzentos e quarenta e nove",
            "duzentos e cinquenta",
            "duzentos e cinquenta e um",
            "duzentos e cinquenta e dois",
            "duzentos e cinquenta e três",
            "duzentos e cinquenta e quatro",
            "duzentos e cinquenta e cinco",
            "duzentos e cinquenta e seis",
            "duzentos e cinquenta e sete",
            "duzentos e cinquenta e oito",
            "duzentos e cinquenta e nove",
            "duzentos e sessenta",
            "duzentos e sessenta e um",
            "duzentos e sessenta e dois",
            "duzentos e sessenta e três",
            "duzentos e sessenta e quatro",
            "duzentos e sessenta e cinco",
            "duzentos e sessenta e seis",
            "duzentos e sessenta e sete",
            "duzentos e sessenta e oito",
            "duzentos e sessenta e nove",
            "duzentos e setenta",
            "duzentos e setenta e um",
            "duzentos e setenta e dois",
            "duzentos e setenta e três",
            "duzentos e setenta e quatro",
            "duzentos e setenta e cinco",
            "duzentos e setenta e seis",
            "duzentos e setenta e sete",
            "duzentos e setenta e oito",
            "duzentos e setenta e nove",
            "duzentos e oitenta",
            "duzentos e oitenta e um",
            "duzentos e oitenta e dois",
            "duzentos e oitenta e três",
            "duzentos e oitenta e quatro",
            "duzentos e oitenta e cinco",
            "duzentos e oitenta e seis",
            "duzentos e oitenta e sete",
            "duzentos e oitenta e oito",
            "duzentos e oitenta e nove",
            "duzentos e noventa",
            "duzentos e noventa e um",
            "duzentos e noventa e dois",
            "duzentos e noventa e três",
            "duzentos e noventa e quatro",
            "duzentos e noventa e cinco",
            "duzentos e noventa e seis",
            "duzentos e noventa e sete",
            "duzentos e noventa e oito",
            "duzentos e noventa e nove",
            "trezentos",
            "trezentos e um",
            "trezentos e dois",
            "trezentos e três",
            "trezentos e quatro",
            "trezentos e cinco",
            "trezentos e seis",
            "trezentos e sete",
            "trezentos e oito",
            "trezentos e nove",
            "trezentos e dez",
            "trezentos e onze",
            "trezentos e doze",
            "trezentos e treze",
            "trezentos e quatorze",
            "trezentos e quinze",
            "trezentos e dezesseis",
            "trezentos e dezessete",
            "trezentos e dezoito",
            "trezentos e dezenove",
            "trezentos e vinte",
            "trezentos e vinte e um",
            "trezentos e vinte e dois",
            "trezentos e vinte e três",
            "trezentos e vinte e quatro",
            "trezentos e vinte e cinco",
            "trezentos e vinte e seis",
            "trezentos e vinte e sete",
            "trezentos e vinte e oito",
            "trezentos e vinte e nove",
            "trezentos e trinta",
            "trezentos e trinta e um",
            "trezentos e trinta e dois",
            "trezentos e trinta e três",
            "trezentos e trinta e quatro",
            "trezentos e trinta e cinco",
            "trezentos e trinta e seis",
            "trezentos e trinta e sete",
            "trezentos e trinta e oito",
            "trezentos e trinta e nove",
            "trezentos e quarenta",
            "trezentos e quarenta e um",
            "trezentos e quarenta e dois",
            "trezentos e quarenta e três",
            "trezentos e quarenta e quatro",
            "trezentos e quarenta e cinco",
            "trezentos e quarenta e seis",
            "trezentos e quarenta e sete",
            "trezentos e quarenta e oito",
            "trezentos e quarenta e nove",
            "trezentos e cinquenta",
            "trezentos e cinquenta e um",
            "trezentos e cinquenta e dois",
            "trezentos e cinquenta e três",
            "trezentos e cinquenta e quatro",
            "trezentos e cinquenta e cinco",
            "trezentos e cinquenta e seis",
            "trezentos e cinquenta e sete",
            "trezentos e cinquenta e oito",
            "trezentos e cinquenta e nove",
            "trezentos e sessenta",
            "trezentos e sessenta e um",
            "trezentos e sessenta e dois",
            "trezentos e sessenta e três",
            "trezentos e sessenta e quatro",
            "trezentos e sessenta e cinco",
            "trezentos e sessenta e seis",
            "trezentos e sessenta e sete",
            "trezentos e sessenta e oito",
            "trezentos e sessenta e nove",
            "trezentos e setenta",
            "trezentos e setenta e um",
            "trezentos e setenta e dois",
            "trezentos e setenta e três",
            "trezentos e setenta e quatro",
            "trezentos e setenta e cinco",
            "trezentos e setenta e seis",
            "trezentos e setenta e sete",
            "trezentos e setenta e oito",
            "trezentos e setenta e nove",
            "trezentos e oitenta",
            "trezentos e oitenta e um",
            "trezentos e oitenta e dois",
            "trezentos e oitenta e três",
            "trezentos e oitenta e quatro",
            "trezentos e oitenta e cinco",
            "trezentos e oitenta e seis",
            "trezentos e oitenta e sete",
            "trezentos e oitenta e oito",
            "trezentos e oitenta e nove",
            "trezentos e noventa",
            "trezentos e noventa e um",
            "trezentos e noventa e dois",
            "trezentos e noventa e três",
            "trezentos e noventa e quatro",
            "trezentos e noventa e cinco",
            "trezentos e noventa e seis",
            "trezentos e noventa e sete",
            "trezentos e noventa e oito",
            "trezentos e noventa e nove",
            "quatrocentos",
            "quatrocentos e um",
            "quatrocentos e dois",
            "quatrocentos e três",
            "quatrocentos e quatro",
            "quatrocentos e cinco",
            "quatrocentos e seis",
            "quatrocentos e sete",
            "quatrocentos e oito",
            "quatrocentos e nove",
            "quatrocentos e dez",
            "quatrocentos e onze",
            "quatrocentos e doze",
            "quatrocentos e treze",
            "quatrocentos e quatorze",
            "quatrocentos e quinze",
            "quatrocentos e dezesseis",
            "quatrocentos e dezessete",
            "quatrocentos e dezoito",
            "quatrocentos e dezenove",
            "quatrocentos e vinte",
            "quatrocentos e vinte e um",
            "quatrocentos e vinte e dois",
            "quatrocentos e vinte e três",
            "quatrocentos e vinte e quatro",
            "quatrocentos e vinte e cinco",
            "quatrocentos e vinte e seis",
            "quatrocentos e vinte e sete",
            "quatrocentos e vinte e oito",
            "quatrocentos e vinte e nove",
            "quatrocentos e trinta",
            "quatrocentos e trinta e um",
            "quatrocentos e trinta e dois",
            "quatrocentos e trinta e três",
            "quatrocentos e trinta e quatro",
            "quatrocentos e trinta e cinco",
            "quatrocentos e trinta e seis",
            "quatrocentos e trinta e sete",
            "quatrocentos e trinta e oito",
            "quatrocentos e trinta e nove",
            "quatrocentos e quarenta",
            "quatrocentos e quarenta e um",
            "quatrocentos e quarenta e dois",
            "quatrocentos e quarenta e três",
            "quatrocentos e quarenta e quatro",
            "quatrocentos e quarenta e cinco",
            "quatrocentos e quarenta e seis",
            "quatrocentos e quarenta e sete",
            "quatrocentos e quarenta e oito",
            "quatrocentos e quarenta e nove",
            "quatrocentos e cinquenta",
            "quatrocentos e cinquenta e um",
            "quatrocentos e cinquenta e dois",
            "quatrocentos e cinquenta e três",
            "quatrocentos e cinquenta e quatro",
            "quatrocentos e cinquenta e cinco",
            "quatrocentos e cinquenta e seis",
            "quatrocentos e cinquenta e sete",
            "quatrocentos e cinquenta e oito",
            "quatrocentos e cinquenta e nove",
            "quatrocentos e sessenta",
            "quatrocentos e sessenta e um",
            "quatrocentos e sessenta e dois",
            "quatrocentos e sessenta e três",
            "quatrocentos e sessenta e quatro",
            "quatrocentos e sessenta e cinco",
            "quatrocentos e sessenta e seis",
            "quatrocentos e sessenta e sete",
            "quatrocentos e sessenta e oito",
            "quatrocentos e sessenta e nove",
            "quatrocentos e setenta",
            "quatrocentos e setenta e um",
            "quatrocentos e setenta e dois",
            "quatrocentos e setenta e três",
            "quatrocentos e setenta e quatro",
            "quatrocentos e setenta e cinco",
            "quatrocentos e setenta e seis",
            "quatrocentos e setenta e sete",
            "quatrocentos e setenta e oito",
            "quatrocentos e setenta e nove",
            "quatrocentos e oitenta",
            "quatrocentos e oitenta e um",
            "quatrocentos e oitenta e dois",
            "quatrocentos e oitenta e três",
            "quatrocentos e oitenta e quatro",
            "quatrocentos e oitenta e cinco",
            "quatrocentos e oitenta e seis",
            "quatrocentos e oitenta e sete",
            "quatrocentos e oitenta e oito",
            "quatrocentos e oitenta e nove",
            "quatrocentos e noventa",
            "quatrocentos e noventa e um",
            "quatrocentos e noventa e dois",
            "quatrocentos e noventa e três",
            "quatrocentos e noventa e quatro",
            "quatrocentos e noventa e cinco",
            "quatrocentos e noventa e seis",
            "quatrocentos e noventa e sete",
            "quatrocentos e noventa e oito",
            "quatrocentos e noventa e nove",
            "quinhentos",
            "quinhentos e um",
            "quinhentos e dois",
            "quinhentos e três",
            "quinhentos e quatro",
            "quinhentos e cinco",
            "quinhentos e seis",
            "quinhentos e sete",
            "quinhentos e oito",
            "quinhentos e nove",
            "quinhentos e dez",
            "quinhentos e onze",
            "quinhentos e doze",
            "quinhentos e treze",
            "quinhentos e quatorze",
            "quinhentos e quinze",
            "quinhentos e dezesseis",
            "quinhentos e dezessete",
            "quinhentos e dezoito",
            "quinhentos e dezenove",
            "quinhentos e vinte",
            "quinhentos e vinte e um",
            "quinhentos e vinte e dois",
            "quinhentos e vinte e três",
            "quinhentos e vinte e quatro",
            "quinhentos e vinte e cinco",
            "quinhentos e vinte e seis",
            "quinhentos e vinte e sete",
            "quinhentos e vinte e oito",
            "quinhentos e vinte e nove",
            "quinhentos e trinta",
            "quinhentos e trinta e um",
            "quinhentos e trinta e dois",
            "quinhentos e trinta e três",
            "quinhentos e trinta e quatro",
            "quinhentos e trinta e cinco",
            "quinhentos e trinta e seis",
            "quinhentos e trinta e sete",
            "quinhentos e trinta e oito",
            "quinhentos e trinta e nove",
            "quinhentos e quarenta",
            "quinhentos e quarenta e um",
            "quinhentos e quarenta e dois",
            "quinhentos e quarenta e três",
            "quinhentos e quarenta e quatro",
            "quinhentos e quarenta e cinco",
            "quinhentos e quarenta e seis",
            "quinhentos e quarenta e sete",
            "quinhentos e quarenta e oito",
            "quinhentos e quarenta e nove",
            "quinhentos e cinquenta",
            "quinhentos e cinquenta e um",
            "quinhentos e cinquenta e dois",
            "quinhentos e cinquenta e três",
            "quinhentos e cinquenta e quatro",
            "quinhentos e cinquenta e cinco",
            "quinhentos e cinquenta e seis",
            "quinhentos e cinquenta e sete",
            "quinhentos e cinquenta e oito",
            "quinhentos e cinquenta e nove",
            "quinhentos e sessenta",
            "quinhentos e sessenta e um",
            "quinhentos e sessenta e dois",
            "quinhentos e sessenta e três",
            "quinhentos e sessenta e quatro",
            "quinhentos e sessenta e cinco",
            "quinhentos e sessenta e seis",
            "quinhentos e sessenta e sete",
            "quinhentos e sessenta e oito",
            "quinhentos e sessenta e nove",
            "quinhentos e setenta",
            "quinhentos e setenta e um",
            "quinhentos e setenta e dois",
            "quinhentos e setenta e três",
            "quinhentos e setenta e quatro",
            "quinhentos e setenta e cinco",
            "quinhentos e setenta e seis",
            "quinhentos e setenta e sete",
            "quinhentos e setenta e oito",
            "quinhentos e setenta e nove",
            "quinhentos e oitenta",
            "quinhentos e oitenta e um",
            "quinhentos e oitenta e dois",
            "quinhentos e oitenta e três",
            "quinhentos e oitenta e quatro",
            "quinhentos e oitenta e cinco",
            "quinhentos e oitenta e seis",
            "quinhentos e oitenta e sete",
            "quinhentos e oitenta e oito",
            "quinhentos e oitenta e nove",
            "quinhentos e noventa",
            "quinhentos e noventa e um",
            "quinhentos e noventa e dois",
            "quinhentos e noventa e três",
            "quinhentos e noventa e quatro",
            "quinhentos e noventa e cinco",
            "quinhentos e noventa e seis",
            "quinhentos e noventa e sete",
            "quinhentos e noventa e oito",
            "quinhentos e noventa e nove",
            "seiscentos",
            "seiscentos e um",
            "seiscentos e dois",
            "seiscentos e três",
            "seiscentos e quatro",
            "seiscentos e cinco",
            "seiscentos e seis",
            "seiscentos e sete",
            "seiscentos e oito",
            "seiscentos e nove",
            "seiscentos e dez",
            "seiscentos e onze",
            "seiscentos e doze",
            "seiscentos e treze",
            "seiscentos e quatorze",
            "seiscentos e quinze",
            "seiscentos e dezesseis",
            "seiscentos e dezessete",
            "seiscentos e dezoito",
            "seiscentos e dezenove",
            "seiscentos e vinte",
            "seiscentos e vinte e um",
            "seiscentos e vinte e dois",
            "seiscentos e vinte e três",
            "seiscentos e vinte e quatro",
            "seiscentos e vinte e cinco",
            "seiscentos e vinte e seis",
            "seiscentos e vinte e sete",
            "seiscentos e vinte e oito",
            "seiscentos e vinte e nove",
            "seiscentos e trinta",
            "seiscentos e trinta e um",
            "seiscentos e trinta e dois",
            "seiscentos e trinta e três",
            "seiscentos e trinta e quatro",
            "seiscentos e trinta e cinco",
            "seiscentos e trinta e seis",
            "seiscentos e trinta e sete",
            "seiscentos e trinta e oito",
            "seiscentos e trinta e nove",
            "seiscentos e quarenta",
            "seiscentos e quarenta e um",
            "seiscentos e quarenta e dois",
            "seiscentos e quarenta e três",
            "seiscentos e quarenta e quatro",
            "seiscentos e quarenta e cinco",
            "seiscentos e quarenta e seis",
            "seiscentos e quarenta e sete",
            "seiscentos e quarenta e oito",
            "seiscentos e quarenta e nove",
            "seiscentos e cinquenta",
            "seiscentos e cinquenta e um",
            "seiscentos e cinquenta e dois",
            "seiscentos e cinquenta e três",
            "seiscentos e cinquenta e quatro",
            "seiscentos e cinquenta e cinco",
            "seiscentos e cinquenta e seis",
            "seiscentos e cinquenta e sete",
            "seiscentos e cinquenta e oito",
            "seiscentos e cinquenta e nove",
            "seiscentos e sessenta",
            "seiscentos e sessenta e um",
            "seiscentos e sessenta e dois",
            "seiscentos e sessenta e três",
            "seiscentos e sessenta e quatro",
            "seiscentos e sessenta e cinco",
            "seiscentos e sessenta e seis",
            "seiscentos e sessenta e sete",
            "seiscentos e sessenta e oito",
            "seiscentos e sessenta e nove",
            "seiscentos e setenta",
            "seiscentos e setenta e um",
            "seiscentos e setenta e dois",
            "seiscentos e setenta e três",
            "seiscentos e setenta e quatro",
            "seiscentos e setenta e cinco",
            "seiscentos e setenta e seis",
            "seiscentos e setenta e sete",
            "seiscentos e setenta e oito",
            "seiscentos e setenta e nove",
            "seiscentos e oitenta",
            "seiscentos e oitenta e um",
            "seiscentos e oitenta e dois",
            "seiscentos e oitenta e três",
            "seiscentos e oitenta e quatro",
            "seiscentos e oitenta e cinco",
            "seiscentos e oitenta e seis",
            "seiscentos e oitenta e sete",
            "seiscentos e oitenta e oito",
            "seiscentos e oitenta e nove",
            "seiscentos e noventa",
            "seiscentos e noventa e um",
            "seiscentos e noventa e dois",
            "seiscentos e noventa e três",
            "seiscentos e noventa e quatro",
            "seiscentos e noventa e cinco",
            "seiscentos e noventa e seis",
            "seiscentos e noventa e sete",
            "seiscentos e noventa e oito",
            "seiscentos e noventa e nove",
            "setecentos",
            "setecentos e um",
            "setecentos e dois",
            "setecentos e três",
            "setecentos e quatro",
            "setecentos e cinco",
            "setecentos e seis",
            "setecentos e sete",
            "setecentos e oito",
            "setecentos e nove",
            "setecentos e dez",
            "setecentos e onze",
            "setecentos e doze",
            "setecentos e treze",
            "setecentos e quatorze",
            "setecentos e quinze",
            "setecentos e dezesseis",
            "setecentos e dezessete",
            "setecentos e dezoito",
            "setecentos e dezenove",
            "setecentos e vinte",
            "setecentos e vinte e um",
            "setecentos e vinte e dois",
            "setecentos e vinte e três",
            "setecentos e vinte e quatro",
            "setecentos e vinte e cinco",
            "setecentos e vinte e seis",
            "setecentos e vinte e sete",
            "setecentos e vinte e oito",
            "setecentos e vinte e nove",
            "setecentos e trinta",
            "setecentos e trinta e um",
            "setecentos e trinta e dois",
            "setecentos e trinta e três",
            "setecentos e trinta e quatro",
            "setecentos e trinta e cinco",
            "setecentos e trinta e seis",
            "setecentos e trinta e sete",
            "setecentos e trinta e oito",
            "setecentos e trinta e nove",
            "setecentos e quarenta",
            "setecentos e quarenta e um",
            "setecentos e quarenta e dois",
            "setecentos e quarenta e três",
            "setecentos e quarenta e quatro",
            "setecentos e quarenta e cinco",
            "setecentos e quarenta e seis",
            "setecentos e quarenta e sete",
            "setecentos e quarenta e oito",
            "setecentos e quarenta e nove",
            "setecentos e cinquenta",
            "setecentos e cinquenta e um",
            "setecentos e cinquenta e dois",
            "setecentos e cinquenta e três",
            "setecentos e cinquenta e quatro",
            "setecentos e cinquenta e cinco",
            "setecentos e cinquenta e seis",
            "setecentos e cinquenta e sete",
            "setecentos e cinquenta e oito",
            "setecentos e cinquenta e nove",
            "setecentos e sessenta",
            "setecentos e sessenta e um",
            "setecentos e sessenta e dois",
            "setecentos e sessenta e três",
            "setecentos e sessenta e quatro",
            "setecentos e sessenta e cinco",
            "setecentos e sessenta e seis",
            "setecentos e sessenta e sete",
            "setecentos e sessenta e oito",
            "setecentos e sessenta e nove",
            "setecentos e setenta",
            "setecentos e setenta e um",
            "setecentos e setenta e dois",
            "setecentos e setenta e três",
            "setecentos e setenta e quatro",
            "setecentos e setenta e cinco",
            "setecentos e setenta e seis",
            "setecentos e setenta e sete",
            "setecentos e setenta e oito",
            "setecentos e setenta e nove",
            "setecentos e oitenta",
            "setecentos e oitenta e um",
            "setecentos e oitenta e dois",
            "setecentos e oitenta e três",
            "setecentos e oitenta e quatro",
            "setecentos e oitenta e cinco",
            "setecentos e oitenta e seis",
            "setecentos e oitenta e sete",
            "setecentos e oitenta e oito",
            "setecentos e oitenta e nove",
            "setecentos e noventa",
            "setecentos e noventa e um",
            "setecentos e noventa e dois",
            "setecentos e noventa e três",
            "setecentos e noventa e quatro",
            "setecentos e noventa e cinco",
            "setecentos e noventa e seis",
            "setecentos e noventa e sete",
            "setecentos e noventa e oito",
            "setecentos e noventa e nove",
            "oitocentos",
            "oitocentos e um",
            "oitocentos e dois",
            "oitocentos e três",
            "oitocentos e quatro",
            "oitocentos e cinco",
            "oitocentos e seis",
            "oitocentos e sete",
            "oitocentos e oito",
            "oitocentos e nove",
            "oitocentos e dez",
            "oitocentos e onze",
            "oitocentos e doze",
            "oitocentos e treze",
            "oitocentos e quatorze",
            "oitocentos e quinze",
            "oitocentos e dezesseis",
            "oitocentos e dezessete",
            "oitocentos e dezoito",
            "oitocentos e dezenove",
            "oitocentos e vinte",
            "oitocentos e vinte e um",
            "oitocentos e vinte e dois",
            "oitocentos e vinte e três",
            "oitocentos e vinte e quatro",
            "oitocentos e vinte e cinco",
            "oitocentos e vinte e seis",
            "oitocentos e vinte e sete",
            "oitocentos e vinte e oito",
            "oitocentos e vinte e nove",
            "oitocentos e trinta",
            "oitocentos e trinta e um",
            "oitocentos e trinta e dois",
            "oitocentos e trinta e três",
            "oitocentos e trinta e quatro",
            "oitocentos e trinta e cinco",
            "oitocentos e trinta e seis",
            "oitocentos e trinta e sete",
            "oitocentos e trinta e oito",
            "oitocentos e trinta e nove",
            "oitocentos e quarenta",
            "oitocentos e quarenta e um",
            "oitocentos e quarenta e dois",
            "oitocentos e quarenta e três",
            "oitocentos e quarenta e quatro",
            "oitocentos e quarenta e cinco",
            "oitocentos e quarenta e seis",
            "oitocentos e quarenta e sete",
            "oitocentos e quarenta e oito",
            "oitocentos e quarenta e nove",
            "oitocentos e cinquenta",
            "oitocentos e cinquenta e um",
            "oitocentos e cinquenta e dois",
            "oitocentos e cinquenta e três",
            "oitocentos e cinquenta e quatro",
            "oitocentos e cinquenta e cinco",
            "oitocentos e cinquenta e seis",
            "oitocentos e cinquenta e sete",
            "oitocentos e cinquenta e oito",
            "oitocentos e cinquenta e nove",
            "oitocentos e sessenta",
            "oitocentos e sessenta e um",
            "oitocentos e sessenta e dois",
            "oitocentos e sessenta e três",
            "oitocentos e sessenta e quatro",
            "oitocentos e sessenta e cinco",
            "oitocentos e sessenta e seis",
            "oitocentos e sessenta e sete",
            "oitocentos e sessenta e oito",
            "oitocentos e sessenta e nove",
            "oitocentos e setenta",
            "oitocentos e setenta e um",
            "oitocentos e setenta e dois",
            "oitocentos e setenta e três",
            "oitocentos e setenta e quatro",
            "oitocentos e setenta e cinco",
            "oitocentos e setenta e seis",
            "oitocentos e setenta e sete",
            "oitocentos e setenta e oito",
            "oitocentos e setenta e nove",
            "oitocentos e oitenta",
            "oitocentos e oitenta e um",
            "oitocentos e oitenta e dois",
            "oitocentos e oitenta e três",
            "oitocentos e oitenta e quatro",
            "oitocentos e oitenta e cinco",
            "oitocentos e oitenta e seis",
            "oitocentos e oitenta e sete",
            "oitocentos e oitenta e oito",
            "oitocentos e oitenta e nove",
            "oitocentos e noventa",
            "oitocentos e noventa e um",
            "oitocentos e noventa e dois",
            "oitocentos e noventa e três",
            "oitocentos e noventa e quatro",
            "oitocentos e noventa e cinco",
            "oitocentos e noventa e seis",
            "oitocentos e noventa e sete",
            "oitocentos e noventa e oito",
            "oitocentos e noventa e nove",
            "novecentos",
            "novecentos e um",
            "novecentos e dois",
            "novecentos e três",
            "novecentos e quatro",
            "novecentos e cinco",
            "novecentos e seis",
            "novecentos e sete",
            "novecentos e oito",
            "novecentos e nove",
            "novecentos e dez",
            "novecentos e onze",
            "novecentos e doze",
            "novecentos e treze",
            "novecentos e quatorze",
            "novecentos e quinze",
            "novecentos e dezesseis",
            "novecentos e dezessete",
            "novecentos e dezoito",
            "novecentos e dezenove",
            "novecentos e vinte",
            "novecentos e vinte e um",
            "novecentos e vinte e dois",
            "novecentos e vinte e três",
            "novecentos e vinte e quatro",
            "novecentos e vinte e cinco",
            "novecentos e vinte e seis",
            "novecentos e vinte e sete",
            "novecentos e vinte e oito",
            "novecentos e vinte e nove",
            "novecentos e trinta",
            "novecentos e trinta e um",
            "novecentos e trinta e dois",
            "novecentos e trinta e três",
            "novecentos e trinta e quatro",
            "novecentos e trinta e cinco",
            "novecentos e trinta e seis",
            "novecentos e trinta e sete",
            "novecentos e trinta e oito",
            "novecentos e trinta e nove",
            "novecentos e quarenta",
            "novecentos e quarenta e um",
            "novecentos e quarenta e dois",
            "novecentos e quarenta e três",
            "novecentos e quarenta e quatro",
            "novecentos e quarenta e cinco",
            "novecentos e quarenta e seis",
            "novecentos e quarenta e sete",
            "novecentos e quarenta e oito",
            "novecentos e quarenta e nove",
            "novecentos e cinquenta",
            "novecentos e cinquenta e um",
            "novecentos e cinquenta e dois",
            "novecentos e cinquenta e três",
            "novecentos e cinquenta e quatro",
            "novecentos e cinquenta e cinco",
            "novecentos e cinquenta e seis",
            "novecentos e cinquenta e sete",
            "novecentos e cinquenta e oito",
            "novecentos e cinquenta e nove",
            "novecentos e sessenta",
            "novecentos e sessenta e um",
            "novecentos e sessenta e dois",
            "novecentos e sessenta e três",
            "novecentos e sessenta e quatro",
            "novecentos e sessenta e cinco",
            "novecentos e sessenta e seis",
            "novecentos e sessenta e sete",
            "novecentos e sessenta e oito",
            "novecentos e sessenta e nove",
            "novecentos e setenta",
            "novecentos e setenta e um",
            "novecentos e setenta e dois",
            "novecentos e setenta e três",
            "novecentos e setenta e quatro",
            "novecentos e setenta e cinco",
            "novecentos e setenta e seis",
            "novecentos e setenta e sete",
            "novecentos e setenta e oito",
            "novecentos e setenta e nove",
            "novecentos e oitenta",
            "novecentos e oitenta e um",
            "novecentos e oitenta e dois",
            "novecentos e oitenta e três",
            "novecentos e oitenta e quatro",
            "novecentos e oitenta e cinco",
            "novecentos e oitenta e seis",
            "novecentos e oitenta e sete",
            "novecentos e oitenta e oito",
            "novecentos e oitenta e nove",
            "novecentos e noventa",
            "novecentos e noventa e um",
            "novecentos e noventa e dois",
            "novecentos e noventa e três",
            "novecentos e noventa e quatro",
            "novecentos e noventa e cinco",
            "novecentos e noventa e seis",
            "novecentos e noventa e sete",
            "novecentos e noventa e oito",
            "novecentos e noventa e nove",
            "mil"
        };
        public static Dictionary<string, int> DicNumeros = new Dictionary<string, int>()
        {
            {"zero",0},
            {"um",1},
            {"dois",2},
            {"três",3},
            {"quatro",4},
            {"cinco",5},
            {"seis",6},
            {"sete",7},
            {"oito",8},
            {"nove",9},
            {"dez",10},
            {"onze",11},
            {"doze",12},
            {"treze",13},
            {"quatorze",14},
            {"quinze",15},
            {"dezesseis",16},
            {"dezessete",17},
            {"dezoito",18},
            {"dezenove",19},
            {"vinte",20},
            {"vinte e um",21},
            {"vinte e dois",22},
            {"vinte e três",23},
            {"vinte e quatro",24},
            {"vinte e cinco",25},
            {"vinte e seis",26},
            {"vinte e sete",27},
            {"vinte e oito",28},
            {"vinte e nove",29},
            {"trinta",30},
            {"trinta e um",31},
            {"trinta e dois",32},
            {"trinta e três",33},
            {"trinta e quatro",34},
            {"trinta e cinco",35},
            {"trinta e seis",36},
            {"trinta e sete",37},
            {"trinta e oito",38},
            {"trinta e nove",39},
            {"quarenta",40},
            {"quarenta e um",41},
            {"quarenta e dois",42},
            {"quarenta e três",43},
            {"quarenta e quatro",44},
            {"quarenta e cinco",45},
            {"quarenta e seis",46},
            {"quarenta e sete",47},
            {"quarenta e oito",48},
            {"quarenta e nove",49},
            {"cinquenta",50},
            {"cinquenta e um",51},
            {"cinquenta e dois",52},
            {"cinquenta e três",53},
            {"cinquenta e quatro",54},
            {"cinquenta e cinco",55},
            {"cinquenta e seis",56},
            {"cinquenta e sete",57},
            {"cinquenta e oito",58},
            {"cinquenta e nove",59},
            {"sessenta",60},
            {"sessenta e um",61},
            {"sessenta e dois",62},
            {"sessenta e três",63},
            {"sessenta e quatro",64},
            {"sessenta e cinco",65},
            {"sessenta e seis",66},
            {"sessenta e sete",67},
            {"sessenta e oito",68},
            {"sessenta e nove",69},
            {"setenta",70},
            {"setenta e um",71},
            {"setenta e dois",72},
            {"setenta e três",73},
            {"setenta e quatro",74},
            {"setenta e cinco",75},
            {"setenta e seis",76},
            {"setenta e sete",77},
            {"setenta e oito",78},
            {"setenta e nove",79},
            {"oitenta",80},
            {"oitenta e um",81},
            {"oitenta e dois",82},
            {"oitenta e três",83},
            {"oitenta e quatro",84},
            {"oitenta e cinco",85},
            {"oitenta e seis",86},
            {"oitenta e sete",87},
            {"oitenta e oito",88},
            {"oitenta e nove",89},
            {"noventa",90},
            {"noventa e um",91},
            {"noventa e dois",92},
            {"noventa e três",93},
            {"noventa e quatro",94},
            {"noventa e cinco",95},
            {"noventa e seis",96},
            {"noventa e sete",97},
            {"noventa e oito",98},
            {"noventa e nove",99},
            {"cem",100},
            {"cento e um",101},
            {"cento e dois",102},
            {"cento e três",103},
            {"cento e quatro",104},
            {"cento e cinco",105},
            {"cento e seis",106},
            {"cento e sete",107},
            {"cento e oito",108},
            {"cento e nove",109},
            {"cento e dez",110},
            {"cento e onze",111},
            {"cento e doze",112},
            {"cento e treze",113},
            {"cento e quatorze",114},
            {"cento e quinze",115},
            {"cento e dezesseis",116},
            {"cento e dezessete",117},
            {"cento e dezoito",118},
            {"cento e dezenove",119},
            {"cento e vinte",120},
            {"cento e vinte e um",121},
            {"cento e vinte e dois",122},
            {"cento e vinte e três",123},
            {"cento e vinte e quatro",124},
            {"cento e vinte e cinco",125},
            {"cento e vinte e seis",126},
            {"cento e vinte e sete",127},
            {"cento e vinte e oito",128},
            {"cento e vinte e nove",129},
            {"cento e trinta",130},
            {"cento e trinta e um",131},
            {"cento e trinta e dois",132},
            {"cento e trinta e três",133},
            {"cento e trinta e quatro",134},
            {"cento e trinta e cinco",135},
            {"cento e trinta e seis",136},
            {"cento e trinta e sete",137},
            {"cento e trinta e oito",138},
            {"cento e trinta e nove",139},
            {"cento e quarenta",140},
            {"cento e quarenta e um",141},
            {"cento e quarenta e dois",142},
            {"cento e quarenta e três",143},
            {"cento e quarenta e quatro",144},
            {"cento e quarenta e cinco",145},
            {"cento e quarenta e seis",146},
            {"cento e quarenta e sete",147},
            {"cento e quarenta e oito",148},
            {"cento e quarenta e nove",149},
            {"cento e cinquenta",150},
            {"cento e cinquenta e um",151},
            {"cento e cinquenta e dois",152},
            {"cento e cinquenta e três",153},
            {"cento e cinquenta e quatro",154},
            {"cento e cinquenta e cinco",155},
            {"cento e cinquenta e seis",156},
            {"cento e cinquenta e sete",157},
            {"cento e cinquenta e oito",158},
            {"cento e cinquenta e nove",159},
            {"cento e sessenta",160},
            {"cento e sessenta e um",161},
            {"cento e sessenta e dois",162},
            {"cento e sessenta e três",163},
            {"cento e sessenta e quatro",164},
            {"cento e sessenta e cinco",165},
            {"cento e sessenta e seis",166},
            {"cento e sessenta e sete",167},
            {"cento e sessenta e oito",168},
            {"cento e sessenta e nove",169},
            {"cento e setenta",170},
            {"cento e setenta e um",171},
            {"cento e setenta e dois",172},
            {"cento e setenta e três",173},
            {"cento e setenta e quatro",174},
            {"cento e setenta e cinco",175},
            {"cento e setenta e seis",176},
            {"cento e setenta e sete",177},
            {"cento e setenta e oito",178},
            {"cento e setenta e nove",179},
            {"cento e oitenta",180},
            {"cento e oitenta e um",181},
            {"cento e oitenta e dois",182},
            {"cento e oitenta e três",183},
            {"cento e oitenta e quatro",184},
            {"cento e oitenta e cinco",185},
            {"cento e oitenta e seis",186},
            {"cento e oitenta e sete",187},
            {"cento e oitenta e oito",188},
            {"cento e oitenta e nove",189},
            {"cento e noventa",190},
            {"cento e noventa e um",191},
            {"cento e noventa e dois",192},
            {"cento e noventa e três",193},
            {"cento e noventa e quatro",194},
            {"cento e noventa e cinco",195},
            {"cento e noventa e seis",196},
            {"cento e noventa e sete",197},
            {"cento e noventa e oito",198},
            {"cento e noventa e nove",199},
            {"duzentos",200},
            {"duzentos e um",201},
            {"duzentos e dois",202},
            {"duzentos e três",203},
            {"duzentos e quatro",204},
            {"duzentos e cinco",205},
            {"duzentos e seis",206},
            {"duzentos e sete",207},
            {"duzentos e oito",208},
            {"duzentos e nove",209},
            {"duzentos e dez",210},
            {"duzentos e onze",211},
            {"duzentos e doze",212},
            {"duzentos e treze",213},
            {"duzentos e quatorze",214},
            {"duzentos e quinze",215},
            {"duzentos e dezesseis",216},
            {"duzentos e dezessete",217},
            {"duzentos e dezoito",218},
            {"duzentos e dezenove",219},
            {"duzentos e vinte",220},
            {"duzentos e vinte e um",221},
            {"duzentos e vinte e dois",222},
            {"duzentos e vinte e três",223},
            {"duzentos e vinte e quatro",224},
            {"duzentos e vinte e cinco",225},
            {"duzentos e vinte e seis",226},
            {"duzentos e vinte e sete",227},
            {"duzentos e vinte e oito",228},
            {"duzentos e vinte e nove",229},
            {"duzentos e trinta",230},
            {"duzentos e trinta e um",231},
            {"duzentos e trinta e dois",232},
            {"duzentos e trinta e três",233},
            {"duzentos e trinta e quatro",234},
            {"duzentos e trinta e cinco",235},
            {"duzentos e trinta e seis",236},
            {"duzentos e trinta e sete",237},
            {"duzentos e trinta e oito",238},
            {"duzentos e trinta e nove",239},
            {"duzentos e quarenta",240},
            {"duzentos e quarenta e um",241},
            {"duzentos e quarenta e dois",242},
            {"duzentos e quarenta e três",243},
            {"duzentos e quarenta e quatro",244},
            {"duzentos e quarenta e cinco",245},
            {"duzentos e quarenta e seis",246},
            {"duzentos e quarenta e sete",247},
            {"duzentos e quarenta e oito",248},
            {"duzentos e quarenta e nove",249},
            {"duzentos e cinquenta",250},
            {"duzentos e cinquenta e um",251},
            {"duzentos e cinquenta e dois",252},
            {"duzentos e cinquenta e três",253},
            {"duzentos e cinquenta e quatro",254},
            {"duzentos e cinquenta e cinco",255},
            {"duzentos e cinquenta e seis",256},
            {"duzentos e cinquenta e sete",257},
            {"duzentos e cinquenta e oito",258},
            {"duzentos e cinquenta e nove",259},
            {"duzentos e sessenta",260},
            {"duzentos e sessenta e um",261},
            {"duzentos e sessenta e dois",262},
            {"duzentos e sessenta e três",263},
            {"duzentos e sessenta e quatro",264},
            {"duzentos e sessenta e cinco",265},
            {"duzentos e sessenta e seis",266},
            {"duzentos e sessenta e sete",267},
            {"duzentos e sessenta e oito",268},
            {"duzentos e sessenta e nove",269},
            {"duzentos e setenta",270},
            {"duzentos e setenta e um",271},
            {"duzentos e setenta e dois",272},
            {"duzentos e setenta e três",273},
            {"duzentos e setenta e quatro",274},
            {"duzentos e setenta e cinco",275},
            {"duzentos e setenta e seis",276},
            {"duzentos e setenta e sete",277},
            {"duzentos e setenta e oito",278},
            {"duzentos e setenta e nove",279},
            {"duzentos e oitenta",280},
            {"duzentos e oitenta e um",281},
            {"duzentos e oitenta e dois",282},
            {"duzentos e oitenta e três",283},
            {"duzentos e oitenta e quatro",284},
            {"duzentos e oitenta e cinco",285},
            {"duzentos e oitenta e seis",286},
            {"duzentos e oitenta e sete",287},
            {"duzentos e oitenta e oito",288},
            {"duzentos e oitenta e nove",289},
            {"duzentos e noventa",290},
            {"duzentos e noventa e um",291},
            {"duzentos e noventa e dois",292},
            {"duzentos e noventa e três",293},
            {"duzentos e noventa e quatro",294},
            {"duzentos e noventa e cinco",295},
            {"duzentos e noventa e seis",296},
            {"duzentos e noventa e sete",297},
            {"duzentos e noventa e oito",298},
            {"duzentos e noventa e nove",299},
            {"trezentos",300},
            {"trezentos e um",301},
            {"trezentos e dois",302},
            {"trezentos e três",303},
            {"trezentos e quatro",304},
            {"trezentos e cinco",305},
            {"trezentos e seis",306},
            {"trezentos e sete",307},
            {"trezentos e oito",308},
            {"trezentos e nove",309},
            {"trezentos e dez",310},
            {"trezentos e onze",311},
            {"trezentos e doze",312},
            {"trezentos e treze",313},
            {"trezentos e quatorze",314},
            {"trezentos e quinze",315},
            {"trezentos e dezesseis",316},
            {"trezentos e dezessete",317},
            {"trezentos e dezoito",318},
            {"trezentos e dezenove",319},
            {"trezentos e vinte",320},
            {"trezentos e vinte e um",321},
            {"trezentos e vinte e dois",322},
            {"trezentos e vinte e três",323},
            {"trezentos e vinte e quatro",324},
            {"trezentos e vinte e cinco",325},
            {"trezentos e vinte e seis",326},
            {"trezentos e vinte e sete",327},
            {"trezentos e vinte e oito",328},
            {"trezentos e vinte e nove",329},
            {"trezentos e trinta",330},
            {"trezentos e trinta e um",331},
            {"trezentos e trinta e dois",332},
            {"trezentos e trinta e três",333},
            {"trezentos e trinta e quatro",334},
            {"trezentos e trinta e cinco",335},
            {"trezentos e trinta e seis",336},
            {"trezentos e trinta e sete",337},
            {"trezentos e trinta e oito",338},
            {"trezentos e trinta e nove",339},
            {"trezentos e quarenta",340},
            {"trezentos e quarenta e um",341},
            {"trezentos e quarenta e dois",342},
            {"trezentos e quarenta e três",343},
            {"trezentos e quarenta e quatro",344},
            {"trezentos e quarenta e cinco",345},
            {"trezentos e quarenta e seis",346},
            {"trezentos e quarenta e sete",347},
            {"trezentos e quarenta e oito",348},
            {"trezentos e quarenta e nove",349},
            {"trezentos e cinquenta",350},
            {"trezentos e cinquenta e um",351},
            {"trezentos e cinquenta e dois",352},
            {"trezentos e cinquenta e três",353},
            {"trezentos e cinquenta e quatro",354},
            {"trezentos e cinquenta e cinco",355},
            {"trezentos e cinquenta e seis",356},
            {"trezentos e cinquenta e sete",357},
            {"trezentos e cinquenta e oito",358},
            {"trezentos e cinquenta e nove",359},
            {"trezentos e sessenta",360},
            {"trezentos e sessenta e um",361},
            {"trezentos e sessenta e dois",362},
            {"trezentos e sessenta e três",363},
            {"trezentos e sessenta e quatro",364},
            {"trezentos e sessenta e cinco",365},
            {"trezentos e sessenta e seis",366},
            {"trezentos e sessenta e sete",367},
            {"trezentos e sessenta e oito",368},
            {"trezentos e sessenta e nove",369},
            {"trezentos e setenta",370},
            {"trezentos e setenta e um",371},
            {"trezentos e setenta e dois",372},
            {"trezentos e setenta e três",373},
            {"trezentos e setenta e quatro",374},
            {"trezentos e setenta e cinco",375},
            {"trezentos e setenta e seis",376},
            {"trezentos e setenta e sete",377},
            {"trezentos e setenta e oito",378},
            {"trezentos e setenta e nove",379},
            {"trezentos e oitenta",380},
            {"trezentos e oitenta e um",381},
            {"trezentos e oitenta e dois",382},
            {"trezentos e oitenta e três",383},
            {"trezentos e oitenta e quatro",384},
            {"trezentos e oitenta e cinco",385},
            {"trezentos e oitenta e seis",386},
            {"trezentos e oitenta e sete",387},
            {"trezentos e oitenta e oito",388},
            {"trezentos e oitenta e nove",389},
            {"trezentos e noventa",390},
            {"trezentos e noventa e um",391},
            {"trezentos e noventa e dois",392},
            {"trezentos e noventa e três",393},
            {"trezentos e noventa e quatro",394},
            {"trezentos e noventa e cinco",395},
            {"trezentos e noventa e seis",396},
            {"trezentos e noventa e sete",397},
            {"trezentos e noventa e oito",398},
            {"trezentos e noventa e nove",399},
            {"quatrocentos",400},
            {"quatrocentos e um",401},
            {"quatrocentos e dois",402},
            {"quatrocentos e três",403},
            {"quatrocentos e quatro",404},
            {"quatrocentos e cinco",405},
            {"quatrocentos e seis",406},
            {"quatrocentos e sete",407},
            {"quatrocentos e oito",408},
            {"quatrocentos e nove",409},
            {"quatrocentos e dez",410},
            {"quatrocentos e onze",411},
            {"quatrocentos e doze",412},
            {"quatrocentos e treze",413},
            {"quatrocentos e quatorze",414},
            {"quatrocentos e quinze",415},
            {"quatrocentos e dezesseis",416},
            {"quatrocentos e dezessete",417},
            {"quatrocentos e dezoito",418},
            {"quatrocentos e dezenove",419},
            {"quatrocentos e vinte",420},
            {"quatrocentos e vinte e um",421},
            {"quatrocentos e vinte e dois",422},
            {"quatrocentos e vinte e três",423},
            {"quatrocentos e vinte e quatro",424},
            {"quatrocentos e vinte e cinco",425},
            {"quatrocentos e vinte e seis",426},
            {"quatrocentos e vinte e sete",427},
            {"quatrocentos e vinte e oito",428},
            {"quatrocentos e vinte e nove",429},
            {"quatrocentos e trinta",430},
            {"quatrocentos e trinta e um",431},
            {"quatrocentos e trinta e dois",432},
            {"quatrocentos e trinta e três",433},
            {"quatrocentos e trinta e quatro",434},
            {"quatrocentos e trinta e cinco",435},
            {"quatrocentos e trinta e seis",436},
            {"quatrocentos e trinta e sete",437},
            {"quatrocentos e trinta e oito",438},
            {"quatrocentos e trinta e nove",439},
            {"quatrocentos e quarenta",440},
            {"quatrocentos e quarenta e um",441},
            {"quatrocentos e quarenta e dois",442},
            {"quatrocentos e quarenta e três",443},
            {"quatrocentos e quarenta e quatro",444},
            {"quatrocentos e quarenta e cinco",445},
            {"quatrocentos e quarenta e seis",446},
            {"quatrocentos e quarenta e sete",447},
            {"quatrocentos e quarenta e oito",448},
            {"quatrocentos e quarenta e nove",449},
            {"quatrocentos e cinquenta",450},
            {"quatrocentos e cinquenta e um",451},
            {"quatrocentos e cinquenta e dois",452},
            {"quatrocentos e cinquenta e três",453},
            {"quatrocentos e cinquenta e quatro",454},
            {"quatrocentos e cinquenta e cinco",455},
            {"quatrocentos e cinquenta e seis",456},
            {"quatrocentos e cinquenta e sete",457},
            {"quatrocentos e cinquenta e oito",458},
            {"quatrocentos e cinquenta e nove",459},
            {"quatrocentos e sessenta",460},
            {"quatrocentos e sessenta e um",461},
            {"quatrocentos e sessenta e dois",462},
            {"quatrocentos e sessenta e três",463},
            {"quatrocentos e sessenta e quatro",464},
            {"quatrocentos e sessenta e cinco",465},
            {"quatrocentos e sessenta e seis",466},
            {"quatrocentos e sessenta e sete",467},
            {"quatrocentos e sessenta e oito",468},
            {"quatrocentos e sessenta e nove",469},
            {"quatrocentos e setenta",470},
            {"quatrocentos e setenta e um",471},
            {"quatrocentos e setenta e dois",472},
            {"quatrocentos e setenta e três",473},
            {"quatrocentos e setenta e quatro",474},
            {"quatrocentos e setenta e cinco",475},
            {"quatrocentos e setenta e seis",476},
            {"quatrocentos e setenta e sete",477},
            {"quatrocentos e setenta e oito",478},
            {"quatrocentos e setenta e nove",479},
            {"quatrocentos e oitenta",480},
            {"quatrocentos e oitenta e um",481},
            {"quatrocentos e oitenta e dois",482},
            {"quatrocentos e oitenta e três",483},
            {"quatrocentos e oitenta e quatro",484},
            {"quatrocentos e oitenta e cinco",485},
            {"quatrocentos e oitenta e seis",486},
            {"quatrocentos e oitenta e sete",487},
            {"quatrocentos e oitenta e oito",488},
            {"quatrocentos e oitenta e nove",489},
            {"quatrocentos e noventa",490},
            {"quatrocentos e noventa e um",491},
            {"quatrocentos e noventa e dois",492},
            {"quatrocentos e noventa e três",493},
            {"quatrocentos e noventa e quatro",494},
            {"quatrocentos e noventa e cinco",495},
            {"quatrocentos e noventa e seis",496},
            {"quatrocentos e noventa e sete",497},
            {"quatrocentos e noventa e oito",498},
            {"quatrocentos e noventa e nove",499},
            {"quinhentos",500},
            {"quinhentos e um",501},
            {"quinhentos e dois",502},
            {"quinhentos e três",503},
            {"quinhentos e quatro",504},
            {"quinhentos e cinco",505},
            {"quinhentos e seis",506},
            {"quinhentos e sete",507},
            {"quinhentos e oito",508},
            {"quinhentos e nove",509},
            {"quinhentos e dez",510},
            {"quinhentos e onze",511},
            {"quinhentos e doze",512},
            {"quinhentos e treze",513},
            {"quinhentos e quatorze",514},
            {"quinhentos e quinze",515},
            {"quinhentos e dezesseis",516},
            {"quinhentos e dezessete",517},
            {"quinhentos e dezoito",518},
            {"quinhentos e dezenove",519},
            {"quinhentos e vinte",520},
            {"quinhentos e vinte e um",521},
            {"quinhentos e vinte e dois",522},
            {"quinhentos e vinte e três",523},
            {"quinhentos e vinte e quatro",524},
            {"quinhentos e vinte e cinco",525},
            {"quinhentos e vinte e seis",526},
            {"quinhentos e vinte e sete",527},
            {"quinhentos e vinte e oito",528},
            {"quinhentos e vinte e nove",529},
            {"quinhentos e trinta",530},
            {"quinhentos e trinta e um",531},
            {"quinhentos e trinta e dois",532},
            {"quinhentos e trinta e três",533},
            {"quinhentos e trinta e quatro",534},
            {"quinhentos e trinta e cinco",535},
            {"quinhentos e trinta e seis",536},
            {"quinhentos e trinta e sete",537},
            {"quinhentos e trinta e oito",538},
            {"quinhentos e trinta e nove",539},
            {"quinhentos e quarenta",540},
            {"quinhentos e quarenta e um",541},
            {"quinhentos e quarenta e dois",542},
            {"quinhentos e quarenta e três",543},
            {"quinhentos e quarenta e quatro",544},
            {"quinhentos e quarenta e cinco",545},
            {"quinhentos e quarenta e seis",546},
            {"quinhentos e quarenta e sete",547},
            {"quinhentos e quarenta e oito",548},
            {"quinhentos e quarenta e nove",549},
            {"quinhentos e cinquenta",550},
            {"quinhentos e cinquenta e um",551},
            {"quinhentos e cinquenta e dois",552},
            {"quinhentos e cinquenta e três",553},
            {"quinhentos e cinquenta e quatro",554},
            {"quinhentos e cinquenta e cinco",555},
            {"quinhentos e cinquenta e seis",556},
            {"quinhentos e cinquenta e sete",557},
            {"quinhentos e cinquenta e oito",558},
            {"quinhentos e cinquenta e nove",559},
            {"quinhentos e sessenta",560},
            {"quinhentos e sessenta e um",561},
            {"quinhentos e sessenta e dois",562},
            {"quinhentos e sessenta e três",563},
            {"quinhentos e sessenta e quatro",564},
            {"quinhentos e sessenta e cinco",565},
            {"quinhentos e sessenta e seis",566},
            {"quinhentos e sessenta e sete",567},
            {"quinhentos e sessenta e oito",568},
            {"quinhentos e sessenta e nove",569},
            {"quinhentos e setenta",570},
            {"quinhentos e setenta e um",571},
            {"quinhentos e setenta e dois",572},
            {"quinhentos e setenta e três",573},
            {"quinhentos e setenta e quatro",574},
            {"quinhentos e setenta e cinco",575},
            {"quinhentos e setenta e seis",576},
            {"quinhentos e setenta e sete",577},
            {"quinhentos e setenta e oito",578},
            {"quinhentos e setenta e nove",579},
            {"quinhentos e oitenta",580},
            {"quinhentos e oitenta e um",581},
            {"quinhentos e oitenta e dois",582},
            {"quinhentos e oitenta e três",583},
            {"quinhentos e oitenta e quatro",584},
            {"quinhentos e oitenta e cinco",585},
            {"quinhentos e oitenta e seis",586},
            {"quinhentos e oitenta e sete",587},
            {"quinhentos e oitenta e oito",588},
            {"quinhentos e oitenta e nove",589},
            {"quinhentos e noventa",590},
            {"quinhentos e noventa e um",591},
            {"quinhentos e noventa e dois",592},
            {"quinhentos e noventa e três",593},
            {"quinhentos e noventa e quatro",594},
            {"quinhentos e noventa e cinco",595},
            {"quinhentos e noventa e seis",596},
            {"quinhentos e noventa e sete",597},
            {"quinhentos e noventa e oito",598},
            {"quinhentos e noventa e nove",599},
            {"seiscentos",600},
            {"seiscentos e um",601},
            {"seiscentos e dois",602},
            {"seiscentos e três",603},
            {"seiscentos e quatro",604},
            {"seiscentos e cinco",605},
            {"seiscentos e seis",606},
            {"seiscentos e sete",607},
            {"seiscentos e oito",608},
            {"seiscentos e nove",609},
            {"seiscentos e dez",610},
            {"seiscentos e onze",611},
            {"seiscentos e doze",612},
            {"seiscentos e treze",613},
            {"seiscentos e quatorze",614},
            {"seiscentos e quinze",615},
            {"seiscentos e dezesseis",616},
            {"seiscentos e dezessete",617},
            {"seiscentos e dezoito",618},
            {"seiscentos e dezenove",619},
            {"seiscentos e vinte",620},
            {"seiscentos e vinte e um",621},
            {"seiscentos e vinte e dois",622},
            {"seiscentos e vinte e três",623},
            {"seiscentos e vinte e quatro",624},
            {"seiscentos e vinte e cinco",625},
            {"seiscentos e vinte e seis",626},
            {"seiscentos e vinte e sete",627},
            {"seiscentos e vinte e oito",628},
            {"seiscentos e vinte e nove",629},
            {"seiscentos e trinta",630},
            {"seiscentos e trinta e um",631},
            {"seiscentos e trinta e dois",632},
            {"seiscentos e trinta e três",633},
            {"seiscentos e trinta e quatro",634},
            {"seiscentos e trinta e cinco",635},
            {"seiscentos e trinta e seis",636},
            {"seiscentos e trinta e sete",637},
            {"seiscentos e trinta e oito",638},
            {"seiscentos e trinta e nove",639},
            {"seiscentos e quarenta",640},
            {"seiscentos e quarenta e um",641},
            {"seiscentos e quarenta e dois",642},
            {"seiscentos e quarenta e três",643},
            {"seiscentos e quarenta e quatro",644},
            {"seiscentos e quarenta e cinco",645},
            {"seiscentos e quarenta e seis",646},
            {"seiscentos e quarenta e sete",647},
            {"seiscentos e quarenta e oito",648},
            {"seiscentos e quarenta e nove",649},
            {"seiscentos e cinquenta",650},
            {"seiscentos e cinquenta e um",651},
            {"seiscentos e cinquenta e dois",652},
            {"seiscentos e cinquenta e três",653},
            {"seiscentos e cinquenta e quatro",654},
            {"seiscentos e cinquenta e cinco",655},
            {"seiscentos e cinquenta e seis",656},
            {"seiscentos e cinquenta e sete",657},
            {"seiscentos e cinquenta e oito",658},
            {"seiscentos e cinquenta e nove",659},
            {"seiscentos e sessenta",660},
            {"seiscentos e sessenta e um",661},
            {"seiscentos e sessenta e dois",662},
            {"seiscentos e sessenta e três",663},
            {"seiscentos e sessenta e quatro",664},
            {"seiscentos e sessenta e cinco",665},
            {"seiscentos e sessenta e seis",666},
            {"seiscentos e sessenta e sete",667},
            {"seiscentos e sessenta e oito",668},
            {"seiscentos e sessenta e nove",669},
            {"seiscentos e setenta",670},
            {"seiscentos e setenta e um",671},
            {"seiscentos e setenta e dois",672},
            {"seiscentos e setenta e três",673},
            {"seiscentos e setenta e quatro",674},
            {"seiscentos e setenta e cinco",675},
            {"seiscentos e setenta e seis",676},
            {"seiscentos e setenta e sete",677},
            {"seiscentos e setenta e oito",678},
            {"seiscentos e setenta e nove",679},
            {"seiscentos e oitenta",680},
            {"seiscentos e oitenta e um",681},
            {"seiscentos e oitenta e dois",682},
            {"seiscentos e oitenta e três",683},
            {"seiscentos e oitenta e quatro",684},
            {"seiscentos e oitenta e cinco",685},
            {"seiscentos e oitenta e seis",686},
            {"seiscentos e oitenta e sete",687},
            {"seiscentos e oitenta e oito",688},
            {"seiscentos e oitenta e nove",689},
            {"seiscentos e noventa",690},
            {"seiscentos e noventa e um",691},
            {"seiscentos e noventa e dois",692},
            {"seiscentos e noventa e três",693},
            {"seiscentos e noventa e quatro",694},
            {"seiscentos e noventa e cinco",695},
            {"seiscentos e noventa e seis",696},
            {"seiscentos e noventa e sete",697},
            {"seiscentos e noventa e oito",698},
            {"seiscentos e noventa e nove",699},
            {"setecentos",700},
            {"setecentos e um",701},
            {"setecentos e dois",702},
            {"setecentos e três",703},
            {"setecentos e quatro",704},
            {"setecentos e cinco",705},
            {"setecentos e seis",706},
            {"setecentos e sete",707},
            {"setecentos e oito",708},
            {"setecentos e nove",709},
            {"setecentos e dez",710},
            {"setecentos e onze",711},
            {"setecentos e doze",712},
            {"setecentos e treze",713},
            {"setecentos e quatorze",714},
            {"setecentos e quinze",715},
            {"setecentos e dezesseis",716},
            {"setecentos e dezessete",717},
            {"setecentos e dezoito",718},
            {"setecentos e dezenove",719},
            {"setecentos e vinte",720},
            {"setecentos e vinte e um",721},
            {"setecentos e vinte e dois",722},
            {"setecentos e vinte e três",723},
            {"setecentos e vinte e quatro",724},
            {"setecentos e vinte e cinco",725},
            {"setecentos e vinte e seis",726},
            {"setecentos e vinte e sete",727},
            {"setecentos e vinte e oito",728},
            {"setecentos e vinte e nove",729},
            {"setecentos e trinta",730},
            {"setecentos e trinta e um",731},
            {"setecentos e trinta e dois",732},
            {"setecentos e trinta e três",733},
            {"setecentos e trinta e quatro",734},
            {"setecentos e trinta e cinco",735},
            {"setecentos e trinta e seis",736},
            {"setecentos e trinta e sete",737},
            {"setecentos e trinta e oito",738},
            {"setecentos e trinta e nove",739},
            {"setecentos e quarenta",740},
            {"setecentos e quarenta e um",741},
            {"setecentos e quarenta e dois",742},
            {"setecentos e quarenta e três",743},
            {"setecentos e quarenta e quatro",744},
            {"setecentos e quarenta e cinco",745},
            {"setecentos e quarenta e seis",746},
            {"setecentos e quarenta e sete",747},
            {"setecentos e quarenta e oito",748},
            {"setecentos e quarenta e nove",749},
            {"setecentos e cinquenta",750},
            {"setecentos e cinquenta e um",751},
            {"setecentos e cinquenta e dois",752},
            {"setecentos e cinquenta e três",753},
            {"setecentos e cinquenta e quatro",754},
            {"setecentos e cinquenta e cinco",755},
            {"setecentos e cinquenta e seis",756},
            {"setecentos e cinquenta e sete",757},
            {"setecentos e cinquenta e oito",758},
            {"setecentos e cinquenta e nove",759},
            {"setecentos e sessenta",760},
            {"setecentos e sessenta e um",761},
            {"setecentos e sessenta e dois",762},
            {"setecentos e sessenta e três",763},
            {"setecentos e sessenta e quatro",764},
            {"setecentos e sessenta e cinco",765},
            {"setecentos e sessenta e seis",766},
            {"setecentos e sessenta e sete",767},
            {"setecentos e sessenta e oito",768},
            {"setecentos e sessenta e nove",769},
            {"setecentos e setenta",770},
            {"setecentos e setenta e um",771},
            {"setecentos e setenta e dois",772},
            {"setecentos e setenta e três",773},
            {"setecentos e setenta e quatro",774},
            {"setecentos e setenta e cinco",775},
            {"setecentos e setenta e seis",776},
            {"setecentos e setenta e sete",777},
            {"setecentos e setenta e oito",778},
            {"setecentos e setenta e nove",779},
            {"setecentos e oitenta",780},
            {"setecentos e oitenta e um",781},
            {"setecentos e oitenta e dois",782},
            {"setecentos e oitenta e três",783},
            {"setecentos e oitenta e quatro",784},
            {"setecentos e oitenta e cinco",785},
            {"setecentos e oitenta e seis",786},
            {"setecentos e oitenta e sete",787},
            {"setecentos e oitenta e oito",788},
            {"setecentos e oitenta e nove",789},
            {"setecentos e noventa",790},
            {"setecentos e noventa e um",791},
            {"setecentos e noventa e dois",792},
            {"setecentos e noventa e três",793},
            {"setecentos e noventa e quatro",794},
            {"setecentos e noventa e cinco",795},
            {"setecentos e noventa e seis",796},
            {"setecentos e noventa e sete",797},
            {"setecentos e noventa e oito",798},
            {"setecentos e noventa e nove",799},
            {"oitocentos",800},
            {"oitocentos e um",801},
            {"oitocentos e dois",802},
            {"oitocentos e três",803},
            {"oitocentos e quatro",804},
            {"oitocentos e cinco",805},
            {"oitocentos e seis",806},
            {"oitocentos e sete",807},
            {"oitocentos e oito",808},
            {"oitocentos e nove",809},
            {"oitocentos e dez",810},
            {"oitocentos e onze",811},
            {"oitocentos e doze",812},
            {"oitocentos e treze",813},
            {"oitocentos e quatorze",814},
            {"oitocentos e quinze",815},
            {"oitocentos e dezesseis",816},
            {"oitocentos e dezessete",817},
            {"oitocentos e dezoito",818},
            {"oitocentos e dezenove",819},
            {"oitocentos e vinte",820},
            {"oitocentos e vinte e um",821},
            {"oitocentos e vinte e dois",822},
            {"oitocentos e vinte e três",823},
            {"oitocentos e vinte e quatro",824},
            {"oitocentos e vinte e cinco",825},
            {"oitocentos e vinte e seis",826},
            {"oitocentos e vinte e sete",827},
            {"oitocentos e vinte e oito",828},
            {"oitocentos e vinte e nove",829},
            {"oitocentos e trinta",830},
            {"oitocentos e trinta e um",831},
            {"oitocentos e trinta e dois",832},
            {"oitocentos e trinta e três",833},
            {"oitocentos e trinta e quatro",834},
            {"oitocentos e trinta e cinco",835},
            {"oitocentos e trinta e seis",836},
            {"oitocentos e trinta e sete",837},
            {"oitocentos e trinta e oito",838},
            {"oitocentos e trinta e nove",839},
            {"oitocentos e quarenta",840},
            {"oitocentos e quarenta e um",841},
            {"oitocentos e quarenta e dois",842},
            {"oitocentos e quarenta e três",843},
            {"oitocentos e quarenta e quatro",844},
            {"oitocentos e quarenta e cinco",845},
            {"oitocentos e quarenta e seis",846},
            {"oitocentos e quarenta e sete",847},
            {"oitocentos e quarenta e oito",848},
            {"oitocentos e quarenta e nove",849},
            {"oitocentos e cinquenta",850},
            {"oitocentos e cinquenta e um",851},
            {"oitocentos e cinquenta e dois",852},
            {"oitocentos e cinquenta e três",853},
            {"oitocentos e cinquenta e quatro",854},
            {"oitocentos e cinquenta e cinco",855},
            {"oitocentos e cinquenta e seis",856},
            {"oitocentos e cinquenta e sete",857},
            {"oitocentos e cinquenta e oito",858},
            {"oitocentos e cinquenta e nove",859},
            {"oitocentos e sessenta",860},
            {"oitocentos e sessenta e um",861},
            {"oitocentos e sessenta e dois",862},
            {"oitocentos e sessenta e três",863},
            {"oitocentos e sessenta e quatro",864},
            {"oitocentos e sessenta e cinco",865},
            {"oitocentos e sessenta e seis",866},
            {"oitocentos e sessenta e sete",867},
            {"oitocentos e sessenta e oito",868},
            {"oitocentos e sessenta e nove",869},
            {"oitocentos e setenta",870},
            {"oitocentos e setenta e um",871},
            {"oitocentos e setenta e dois",872},
            {"oitocentos e setenta e três",873},
            {"oitocentos e setenta e quatro",874},
            {"oitocentos e setenta e cinco",875},
            {"oitocentos e setenta e seis",876},
            {"oitocentos e setenta e sete",877},
            {"oitocentos e setenta e oito",878},
            {"oitocentos e setenta e nove",879},
            {"oitocentos e oitenta",880},
            {"oitocentos e oitenta e um",881},
            {"oitocentos e oitenta e dois",882},
            {"oitocentos e oitenta e três",883},
            {"oitocentos e oitenta e quatro",884},
            {"oitocentos e oitenta e cinco",885},
            {"oitocentos e oitenta e seis",886},
            {"oitocentos e oitenta e sete",887},
            {"oitocentos e oitenta e oito",888},
            {"oitocentos e oitenta e nove",889},
            {"oitocentos e noventa",890},
            {"oitocentos e noventa e um",891},
            {"oitocentos e noventa e dois",892},
            {"oitocentos e noventa e três",893},
            {"oitocentos e noventa e quatro",894},
            {"oitocentos e noventa e cinco",895},
            {"oitocentos e noventa e seis",896},
            {"oitocentos e noventa e sete",897},
            {"oitocentos e noventa e oito",898},
            {"oitocentos e noventa e nove",899},
            {"novecentos",900},
            {"novecentos e um",901},
            {"novecentos e dois",902},
            {"novecentos e três",903},
            {"novecentos e quatro",904},
            {"novecentos e cinco",905},
            {"novecentos e seis",906},
            {"novecentos e sete",907},
            {"novecentos e oito",908},
            {"novecentos e nove",909},
            {"novecentos e dez",910},
            {"novecentos e onze",911},
            {"novecentos e doze",912},
            {"novecentos e treze",913},
            {"novecentos e quatorze",914},
            {"novecentos e quinze",915},
            {"novecentos e dezesseis",916},
            {"novecentos e dezessete",917},
            {"novecentos e dezoito",918},
            {"novecentos e dezenove",919},
            {"novecentos e vinte",920},
            {"novecentos e vinte e um",921},
            {"novecentos e vinte e dois",922},
            {"novecentos e vinte e três",923},
            {"novecentos e vinte e quatro",924},
            {"novecentos e vinte e cinco",925},
            {"novecentos e vinte e seis",926},
            {"novecentos e vinte e sete",927},
            {"novecentos e vinte e oito",928},
            {"novecentos e vinte e nove",929},
            {"novecentos e trinta",930},
            {"novecentos e trinta e um",931},
            {"novecentos e trinta e dois",932},
            {"novecentos e trinta e três",933},
            {"novecentos e trinta e quatro",934},
            {"novecentos e trinta e cinco",935},
            {"novecentos e trinta e seis",936},
            {"novecentos e trinta e sete",937},
            {"novecentos e trinta e oito",938},
            {"novecentos e trinta e nove",939},
            {"novecentos e quarenta",940},
            {"novecentos e quarenta e um",941},
            {"novecentos e quarenta e dois",942},
            {"novecentos e quarenta e três",943},
            {"novecentos e quarenta e quatro",944},
            {"novecentos e quarenta e cinco",945},
            {"novecentos e quarenta e seis",946},
            {"novecentos e quarenta e sete",947},
            {"novecentos e quarenta e oito",948},
            {"novecentos e quarenta e nove",949},
            {"novecentos e cinquenta",950},
            {"novecentos e cinquenta e um",951},
            {"novecentos e cinquenta e dois",952},
            {"novecentos e cinquenta e três",953},
            {"novecentos e cinquenta e quatro",954},
            {"novecentos e cinquenta e cinco",955},
            {"novecentos e cinquenta e seis",956},
            {"novecentos e cinquenta e sete",957},
            {"novecentos e cinquenta e oito",958},
            {"novecentos e cinquenta e nove",959},
            {"novecentos e sessenta",960},
            {"novecentos e sessenta e um",961},
            {"novecentos e sessenta e dois",962},
            {"novecentos e sessenta e três",963},
            {"novecentos e sessenta e quatro",964},
            {"novecentos e sessenta e cinco",965},
            {"novecentos e sessenta e seis",966},
            {"novecentos e sessenta e sete",967},
            {"novecentos e sessenta e oito",968},
            {"novecentos e sessenta e nove",969},
            {"novecentos e setenta",970},
            {"novecentos e setenta e um",971},
            {"novecentos e setenta e dois",972},
            {"novecentos e setenta e três",973},
            {"novecentos e setenta e quatro",974},
            {"novecentos e setenta e cinco",975},
            {"novecentos e setenta e seis",976},
            {"novecentos e setenta e sete",977},
            {"novecentos e setenta e oito",978},
            {"novecentos e setenta e nove",979},
            {"novecentos e oitenta",980},
            {"novecentos e oitenta e um",981},
            {"novecentos e oitenta e dois",982},
            {"novecentos e oitenta e três",983},
            {"novecentos e oitenta e quatro",984},
            {"novecentos e oitenta e cinco",985},
            {"novecentos e oitenta e seis",986},
            {"novecentos e oitenta e sete",987},
            {"novecentos e oitenta e oito",988},
            {"novecentos e oitenta e nove",989},
            {"novecentos e noventa",990},
            {"novecentos e noventa e um",991},
            {"novecentos e noventa e dois",992},
            {"novecentos e noventa e três",993},
            {"novecentos e noventa e quatro",994},
            {"novecentos e noventa e cinco",995},
            {"novecentos e noventa e seis",996},
            {"novecentos e noventa e sete",997},
            {"novecentos e noventa e oito",998},
            {"novecentos e noventa e nove",999},
            {"mil",1000}
        };
        public static List<string> Operadores = new List<string>()
        {
            "mais",
            "menos",
            "vezes",
            "dividido por",
            "elevado á",
            "raiz de"
        };
        #endregion
        #region Sistema
        public static List<string> QueHorasSao = new List<string>()
        {
            "Que horas são",
            "Quantas horas"
        };
        public static List<string> Quediae = new List<string>()
        {
            "Que dia é hoje",
            "Qual o dia de hoje",
            "Qual a data de hoje"
        };
        public static List<string> PareDeOuvir = new List<string>()
        {
            "Modo silencioso",
            "Mudo"
        };
        public static List<string> VolteAOuvir = new List<string>()
        {
            "Amanda"
        };
        #endregion
        #region Saudações
        public static List<string> Oi = new List<string>()
        {
            "Oi",
            "Oi, Amanda",
            "Olá",
            "Aló"
        };
        public static List<string> BomDia = new List<string>()
        {
            "Bom dia",
            "Bom dia Amanda"
        };
        public static List<string> BoaTarde = new List<string>()
        {
            "Boa Tarde",
            "Bom Tarde Amanda"
        };
        public static List<string> BoaNoite = new List<string>()
        {
            "Boa Noite",
            "Bom Noite Amanda"
        };
        public static List<string> TudoBem = new List<string>()
        {
            "Tudo bem",
            "Tudo e com você",
            "Tudo bem com você"
        };
        public static List<string> despedida = new List<string>()
        {
            "Tchau",
            "tchau Amanda"
        };
        public static List<string> prazer = new List<string>()
        {
            "É um prazer te conhecer",
            "Foi um prazer te conhecer",
            "prazer em te conhecer Amanda"
        };
        public static List<string> nome = new List<string>()
        {
            "Amanda"
        };






        #endregion
        #region Clima e tempo
        public static List<string> QualATemperatura = new List<string>()
        {
            "Qual a temperatura de hoje",
            "Me fale a temperatura de hoje",
            "Diga me a temperatura de hoje",
            "Está fazendo quantos graus lá fora",
            "Está fazendo quantos graus hoje",
            "Quantos graus está fazendo lá fora",
            "Quantos graus está fazendo hoje"
        };
        public static List<string> InfoCity = new List<string>()
        {
            "Me de as informações da cidade",
            "Me fale as informações da cidade",
            "Me diga as informações da cidade",
            "Informações da cidade"
        };
        public static List<string> AllInfos = new List<string>()
        {
            "Me de todas as informações da cidade",
            "Me fale todas as informações da cidade",
            "Me diga todas as informações da cidade",
            "Todas as informações da cidade"
        };
        #endregion
    }
}
